<?xml version="1.0"?>
<robot name="ddrive" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:macro name="frictionless" params="link">
    <gazebo reference="${link}">
      <mu1>0.0</mu1>
      <mu2>0.0</mu2>
    </gazebo>
  </xacro:macro>

  <xacro:frictionless link="caster_bottom"/>
  <xacro:frictionless link="caster_top"/>

  <gazebo reference="base_link"><material>Gazebo/Blue</material></gazebo>
  <gazebo reference="wheel_left"><material>Gazebo/Black</material></gazebo>
  <gazebo reference="wheel_right"><material>Gazebo/Black</material></gazebo>
  <gazebo reference="caster_bottom"><material>Gazebo/Gray</material></gazebo>
  <gazebo reference="caster_top"><material>Gazebo/Gray</material></gazebo>

  <gazebo>
    <plugin name="gz::sim::systems::DiffDrive" filename="gz-sim-diff-drive-system">
      <left_joint>wheel_left_joint</left_joint>
      <right_joint>wheel_right_joint</right_joint>

      <wheel_separation>${2*wh_y}</wheel_separation>
      <wheel_radius>${wh_r}</wheel_radius>

      <cmd_vel_topic>/model/ddrive/cmd_vel</cmd_vel_topic>
      <odom_topic>/model/ddrive/odometry</odom_topic>

      <frame_id>odom</frame_id>
      <child_frame_id>base_link</child_frame_id>
    </plugin>
    <plugin name="gz::sim::systems::JointStatePublisher" filename="gz-sim-joint-state-publisher-system">
        <joint>wheel_left_joint</joint>
        <joint>wheel_right_joint</joint>
    </plugin> 
  </gazebo>

</robot>
